/*
 * This file is generated by jOOQ.
 */
package ru.roksard.jooqgenerated.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.roksard.jooqgenerated.Indexes;
import ru.roksard.jooqgenerated.Keys;
import ru.roksard.jooqgenerated.Public;
import ru.roksard.jooqgenerated.tables.records.OrganisationChildRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationChild extends TableImpl<OrganisationChildRecord> {

    private static final long serialVersionUID = -1088467251;

    /**
     * The reference instance of <code>public.organisation_child</code>
     */
    public static final OrganisationChild ORGANISATION_CHILD = new OrganisationChild();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganisationChildRecord> getRecordType() {
        return OrganisationChildRecord.class;
    }

    /**
     * The column <code>public.organisation_child.parent_id</code>.
     */
    public final TableField<OrganisationChildRecord, Integer> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.organisation_child.child_id</code>.
     */
    public final TableField<OrganisationChildRecord, Integer> CHILD_ID = createField("child_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.organisation_child</code> table reference
     */
    public OrganisationChild() {
        this(DSL.name("organisation_child"), null);
    }

    /**
     * Create an aliased <code>public.organisation_child</code> table reference
     */
    public OrganisationChild(String alias) {
        this(DSL.name(alias), ORGANISATION_CHILD);
    }

    /**
     * Create an aliased <code>public.organisation_child</code> table reference
     */
    public OrganisationChild(Name alias) {
        this(alias, ORGANISATION_CHILD);
    }

    private OrganisationChild(Name alias, Table<OrganisationChildRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrganisationChild(Name alias, Table<OrganisationChildRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OrganisationChild(Table<O> child, ForeignKey<O, OrganisationChildRecord> key) {
        super(child, key, ORGANISATION_CHILD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORGANISATION_CHILD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrganisationChildRecord> getPrimaryKey() {
        return Keys.ORGANISATION_CHILD_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrganisationChildRecord>> getKeys() {
        return Arrays.<UniqueKey<OrganisationChildRecord>>asList(Keys.ORGANISATION_CHILD_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrganisationChildRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrganisationChildRecord, ?>>asList(Keys.ORGANISATION_CHILD__FK_PARENT, Keys.ORGANISATION_CHILD__FK_CHILD);
    }

    public Organisations organisationChild_FkParent() {
        return new Organisations(this, Keys.ORGANISATION_CHILD__FK_PARENT);
    }

    public Organisations organisationChild_FkChild() {
        return new Organisations(this, Keys.ORGANISATION_CHILD__FK_CHILD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationChild as(String alias) {
        return new OrganisationChild(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationChild as(Name alias) {
        return new OrganisationChild(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationChild rename(String name) {
        return new OrganisationChild(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganisationChild rename(Name name) {
        return new OrganisationChild(name, null);
    }
}
