/*
 * This file is generated by jOOQ.
 */
package ru.roksard.jooqgenerated;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.roksard.jooqgenerated.tables.Author;
import ru.roksard.jooqgenerated.tables.AuthorBook;
import ru.roksard.jooqgenerated.tables.Book;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_PKEY = Indexes0.AUTHOR_PKEY;
    public static final Index AUTHOR_BOOK_PKEY = Indexes0.AUTHOR_BOOK_PKEY;
    public static final Index BOOK_PKEY = Indexes0.BOOK_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHOR_PKEY = Internal.createIndex("author_pkey", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index AUTHOR_BOOK_PKEY = Internal.createIndex("author_book_pkey", AuthorBook.AUTHOR_BOOK, new OrderField[] { AuthorBook.AUTHOR_BOOK.AUTHOR_ID, AuthorBook.AUTHOR_BOOK.BOOK_ID }, true);
        public static Index BOOK_PKEY = Internal.createIndex("book_pkey", Book.BOOK, new OrderField[] { Book.BOOK.ID }, true);
    }
}
