/*
 * This file is generated by jOOQ.
 */
package ru.roksard.jooqgenerated;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ru.roksard.jooqgenerated.tables.EmployeeChild;
import ru.roksard.jooqgenerated.tables.Employees;
import ru.roksard.jooqgenerated.tables.OrganisationChild;
import ru.roksard.jooqgenerated.tables.OrganisationEmployee;
import ru.roksard.jooqgenerated.tables.Organisations;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EMPLOYEE_CHILD_PKEY = Indexes0.EMPLOYEE_CHILD_PKEY;
    public static final Index EMPLOYEES_PKEY = Indexes0.EMPLOYEES_PKEY;
    public static final Index ORGANISATION_CHILD_PKEY = Indexes0.ORGANISATION_CHILD_PKEY;
    public static final Index ORGANISATION_EMPLOYEE_PKEY = Indexes0.ORGANISATION_EMPLOYEE_PKEY;
    public static final Index ORGANISATIONS_PKEY = Indexes0.ORGANISATIONS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EMPLOYEE_CHILD_PKEY = Internal.createIndex("employee_child_pkey", EmployeeChild.EMPLOYEE_CHILD, new OrderField[] { EmployeeChild.EMPLOYEE_CHILD.PARENT_ID, EmployeeChild.EMPLOYEE_CHILD.CHILD_ID }, true);
        public static Index EMPLOYEES_PKEY = Internal.createIndex("employees_pkey", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.ID }, true);
        public static Index ORGANISATION_CHILD_PKEY = Internal.createIndex("organisation_child_pkey", OrganisationChild.ORGANISATION_CHILD, new OrderField[] { OrganisationChild.ORGANISATION_CHILD.PARENT_ID, OrganisationChild.ORGANISATION_CHILD.CHILD_ID }, true);
        public static Index ORGANISATION_EMPLOYEE_PKEY = Internal.createIndex("organisation_employee_pkey", OrganisationEmployee.ORGANISATION_EMPLOYEE, new OrderField[] { OrganisationEmployee.ORGANISATION_EMPLOYEE.ORGANISATION_ID, OrganisationEmployee.ORGANISATION_EMPLOYEE.EMPLOYEE_ID }, true);
        public static Index ORGANISATIONS_PKEY = Internal.createIndex("organisations_pkey", Organisations.ORGANISATIONS, new OrderField[] { Organisations.ORGANISATIONS.ID }, true);
    }
}
