/*
 * This file is generated by jOOQ.
 */
package ru.roksard.jooqgenerated;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.roksard.jooqgenerated.tables.Author;
import ru.roksard.jooqgenerated.tables.AuthorBook;
import ru.roksard.jooqgenerated.tables.Book;
import ru.roksard.jooqgenerated.tables.records.AuthorBookRecord;
import ru.roksard.jooqgenerated.tables.records.AuthorRecord;
import ru.roksard.jooqgenerated.tables.records.BookRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = UniqueKeys0.AUTHOR_PKEY;
    public static final UniqueKey<AuthorBookRecord> AUTHOR_BOOK_PKEY = UniqueKeys0.AUTHOR_BOOK_PKEY;
    public static final UniqueKey<BookRecord> BOOK_PKEY = UniqueKeys0.BOOK_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthorBookRecord, AuthorRecord> AUTHOR_BOOK__FK_AB_AUTHOR = ForeignKeys0.AUTHOR_BOOK__FK_AB_AUTHOR;
    public static final ForeignKey<AuthorBookRecord, BookRecord> AUTHOR_BOOK__FK_AB_BOOK = ForeignKeys0.AUTHOR_BOOK__FK_AB_BOOK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = Internal.createUniqueKey(Author.AUTHOR, "author_pkey", Author.AUTHOR.ID);
        public static final UniqueKey<AuthorBookRecord> AUTHOR_BOOK_PKEY = Internal.createUniqueKey(AuthorBook.AUTHOR_BOOK, "author_book_pkey", AuthorBook.AUTHOR_BOOK.AUTHOR_ID, AuthorBook.AUTHOR_BOOK.BOOK_ID);
        public static final UniqueKey<BookRecord> BOOK_PKEY = Internal.createUniqueKey(Book.BOOK, "book_pkey", Book.BOOK.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AuthorBookRecord, AuthorRecord> AUTHOR_BOOK__FK_AB_AUTHOR = Internal.createForeignKey(ru.roksard.jooqgenerated.Keys.AUTHOR_PKEY, AuthorBook.AUTHOR_BOOK, "author_book__fk_ab_author", AuthorBook.AUTHOR_BOOK.AUTHOR_ID);
        public static final ForeignKey<AuthorBookRecord, BookRecord> AUTHOR_BOOK__FK_AB_BOOK = Internal.createForeignKey(ru.roksard.jooqgenerated.Keys.BOOK_PKEY, AuthorBook.AUTHOR_BOOK, "author_book__fk_ab_book", AuthorBook.AUTHOR_BOOK.BOOK_ID);
    }
}
