/*
 * This file is generated by jOOQ.
 */
package ru.roksard.jooqgenerated;


import javax.annotation.Generated;

import ru.roksard.jooqgenerated.tables.EmployeeChild;
import ru.roksard.jooqgenerated.tables.Employees;
import ru.roksard.jooqgenerated.tables.OrganisationChild;
import ru.roksard.jooqgenerated.tables.OrganisationEmployee;
import ru.roksard.jooqgenerated.tables.Organisations;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.employee_child</code>.
     */
    public static final EmployeeChild EMPLOYEE_CHILD = ru.roksard.jooqgenerated.tables.EmployeeChild.EMPLOYEE_CHILD;

    /**
     * The table <code>public.employees</code>.
     */
    public static final Employees EMPLOYEES = ru.roksard.jooqgenerated.tables.Employees.EMPLOYEES;

    /**
     * The table <code>public.organisation_child</code>.
     */
    public static final OrganisationChild ORGANISATION_CHILD = ru.roksard.jooqgenerated.tables.OrganisationChild.ORGANISATION_CHILD;

    /**
     * The table <code>public.organisation_employee</code>.
     */
    public static final OrganisationEmployee ORGANISATION_EMPLOYEE = ru.roksard.jooqgenerated.tables.OrganisationEmployee.ORGANISATION_EMPLOYEE;

    /**
     * The table <code>public.organisations</code>.
     */
    public static final Organisations ORGANISATIONS = ru.roksard.jooqgenerated.tables.Organisations.ORGANISATIONS;
}
