/*
 * This file is generated by jOOQ.
 */
package ru.roksard.empdb.jooqgenerated;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.roksard.empdb.jooqgenerated.tables.EmployeeChild;
import ru.roksard.empdb.jooqgenerated.tables.Employees;
import ru.roksard.empdb.jooqgenerated.tables.OrganisationChild;
import ru.roksard.empdb.jooqgenerated.tables.OrganisationEmployee;
import ru.roksard.empdb.jooqgenerated.tables.Organisations;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -926146289;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.employee_child</code>.
     */
    public final EmployeeChild EMPLOYEE_CHILD = ru.roksard.empdb.jooqgenerated.tables.EmployeeChild.EMPLOYEE_CHILD;

    /**
     * The table <code>public.employees</code>.
     */
    public final Employees EMPLOYEES = ru.roksard.empdb.jooqgenerated.tables.Employees.EMPLOYEES;

    /**
     * The table <code>public.organisation_child</code>.
     */
    public final OrganisationChild ORGANISATION_CHILD = ru.roksard.empdb.jooqgenerated.tables.OrganisationChild.ORGANISATION_CHILD;

    /**
     * The table <code>public.organisation_employee</code>.
     */
    public final OrganisationEmployee ORGANISATION_EMPLOYEE = ru.roksard.empdb.jooqgenerated.tables.OrganisationEmployee.ORGANISATION_EMPLOYEE;

    /**
     * The table <code>public.organisations</code>.
     */
    public final Organisations ORGANISATIONS = ru.roksard.empdb.jooqgenerated.tables.Organisations.ORGANISATIONS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.EMPLOYEES_ID_SEQ,
            Sequences.ORGANISATIONS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            EmployeeChild.EMPLOYEE_CHILD,
            Employees.EMPLOYEES,
            OrganisationChild.ORGANISATION_CHILD,
            OrganisationEmployee.ORGANISATION_EMPLOYEE,
            Organisations.ORGANISATIONS);
    }
}
