/*
 * This file is generated by jOOQ.
 */
package ru.roksard.empdb.jooqgenerated.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.roksard.empdb.jooqgenerated.tables.EmployeeChild;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeChildRecord extends UpdatableRecordImpl<EmployeeChildRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1975980647;

    /**
     * Setter for <code>public.employee_child.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employee_child.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.employee_child.child_id</code>.
     */
    public void setChildId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employee_child.child_id</code>.
     */
    public Integer getChildId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EmployeeChild.EMPLOYEE_CHILD.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EmployeeChild.EMPLOYEE_CHILD.CHILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getChildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getChildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeChildRecord value1(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeChildRecord value2(Integer value) {
        setChildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeeChildRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeChildRecord
     */
    public EmployeeChildRecord() {
        super(EmployeeChild.EMPLOYEE_CHILD);
    }

    /**
     * Create a detached, initialised EmployeeChildRecord
     */
    public EmployeeChildRecord(Integer parentId, Integer childId) {
        super(EmployeeChild.EMPLOYEE_CHILD);

        set(0, parentId);
        set(1, childId);
    }
}
