/*
 * This file is generated by jOOQ.
 */
package ru.roksard.empdb.jooqgenerated.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import ru.roksard.empdb.jooqgenerated.tables.Employees;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 933164680;

    /**
     * Setter for <code>public.employees.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employees.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.employees.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employees.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.employees.organisationid</code>.
     */
    public void setOrganisationid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.employees.organisationid</code>.
     */
    public Integer getOrganisationid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.employees.parentid</code>.
     */
    public void setParentid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.employees.parentid</code>.
     */
    public Integer getParentid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Employees.EMPLOYEES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employees.EMPLOYEES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Employees.EMPLOYEES.ORGANISATIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Employees.EMPLOYEES.PARENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOrganisationid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrganisationid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getParentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value3(Integer value) {
        setOrganisationid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value4(Integer value) {
        setParentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Integer id, String name, Integer organisationid, Integer parentid) {
        super(Employees.EMPLOYEES);

        set(0, id);
        set(1, name);
        set(2, organisationid);
        set(3, parentid);
    }
}
