/*
 * This file is generated by jOOQ.
 */
package ru.roksard.empdb.jooqgenerated.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.roksard.empdb.jooqgenerated.tables.OrganisationEmployee;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationEmployeeRecord extends UpdatableRecordImpl<OrganisationEmployeeRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1392697523;

    /**
     * Setter for <code>public.organisation_employee.organisation_id</code>.
     */
    public void setOrganisationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.organisation_employee.organisation_id</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.organisation_employee.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.organisation_employee.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrganisationEmployee.ORGANISATION_EMPLOYEE.ORGANISATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrganisationEmployee.ORGANISATION_EMPLOYEE.EMPLOYEE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOrganisationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrganisationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEmployeeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationEmployeeRecord value1(Integer value) {
        setOrganisationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationEmployeeRecord value2(Integer value) {
        setEmployeeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationEmployeeRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationEmployeeRecord
     */
    public OrganisationEmployeeRecord() {
        super(OrganisationEmployee.ORGANISATION_EMPLOYEE);
    }

    /**
     * Create a detached, initialised OrganisationEmployeeRecord
     */
    public OrganisationEmployeeRecord(Integer organisationId, Integer employeeId) {
        super(OrganisationEmployee.ORGANISATION_EMPLOYEE);

        set(0, organisationId);
        set(1, employeeId);
    }
}
