/*
 * This file is generated by jOOQ.
 */
package ru.roksard.empdb.jooqgenerated.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.roksard.empdb.jooqgenerated.tables.OrganisationChild;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganisationChildRecord extends UpdatableRecordImpl<OrganisationChildRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1588868337;

    /**
     * Setter for <code>public.organisation_child.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.organisation_child.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.organisation_child.child_id</code>.
     */
    public void setChildId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.organisation_child.child_id</code>.
     */
    public Integer getChildId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrganisationChild.ORGANISATION_CHILD.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrganisationChild.ORGANISATION_CHILD.CHILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getChildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getChildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationChildRecord value1(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationChildRecord value2(Integer value) {
        setChildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganisationChildRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganisationChildRecord
     */
    public OrganisationChildRecord() {
        super(OrganisationChild.ORGANISATION_CHILD);
    }

    /**
     * Create a detached, initialised OrganisationChildRecord
     */
    public OrganisationChildRecord(Integer parentId, Integer childId) {
        super(OrganisationChild.ORGANISATION_CHILD);

        set(0, parentId);
        set(1, childId);
    }
}
